// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://supabase-6421997917235322.kloudbeansite.com";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqenJwZnpxaHB4emNraHRlc2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mjk5MjcsImV4cCI6MjA2NjAwNTkyN30.SVrzRHJjg1XydcUP5DrqvoR7KnnyI7igu5254xng2kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);